#! /bin/sh
#
# insert kbus and make sure everyone is allowed to access it.

case "$1" in
    start)
        if [ ! -e /dev/kbus0 ]; then
            echo -n "Inserting KBus module .. "
            insmod $RAW_DIR/lib/modules/kbus/kbus.ko
            echo "Done"
        fi
        echo -n "Setting permissions .. "
        chmod 666 /dev/kbus0
        echo "Done."
        ;;
    stop)
        echo  "Nothing to do on stop";
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Syntax: kbus [stop|start|restart]"
        ;;
esac

exit 0;
